// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RolesTest2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolesTest2));
        
        string IMigrationMetadata.Id
        {
            get { return "202408281805022_RolesTest2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
